#!/usr/bin/env bash
# This script pings the passed IP address five times

if [ $1 == ""];
then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	for (( i = 1; i<=5; i++));
	do
		ping $1
	done
fi
