#!/usr/bin/env bash
# This script change IP address in the hosts file

cp /etc/hosts /hosts.new
sed -i s/127.0.0.1/127.0.0.2/ /hosts.new
echo "8.8.8.8	facebook.com" >> /hosts.new
cp -f /hosts.new /etc/hosts
